version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pl.allegro.tech.build.axion-release
    versions:
    - 1.13.1
  - dependency-name: com.gradle.plugin-publish
    versions:
    - 0.13.0
